#!/bin/bash
set -euo pipefail
rm -f go.mod go.sum
go mod init github.com/eisenstatdavid/tools
go mod tidy
go fmt ./...
for f in {cmd,internal}/*/*.go; do diff -u /dev/null "$f" || test "$?" -eq 1; done | fill-changed-comments
go fmt ./...
scripts/pretty-mk Makefile
set-shebang /bin/bash -- scripts/*
scripts/pretty-sh scripts/*
