#!/bin/bash
set -euo pipefail
rm -f go.mod go.sum
go mod init github.com/eisenstatdavid/tools
go mod tidy
go fmt ./...
find . -name '*.go' -exec diff -u /dev/null {} \; | fill-changed-comments
go fmt ./...
scripts/pretty-mk Makefile
set-shebang /bin/bash -- scripts/*
scripts/pretty-sh scripts/*
