#!/bin/bash
set -euo pipefail
for f in "$@"; do diff -u /dev/null "${f}" || test "$?" -eq 1; done | squash-strings
clang-format -i "$@"
for f in "$@"; do diff -u /dev/null "${f}" || test "$?" -eq 1; done | fill-changed-comments
clang-format -i "$@"
