#!/bin/bash
brew="/opt/homebrew/bin/brew"
[ -f "${brew}" ] && . <("${brew}" shellenv)
EDITOR="$(command -v vim)"
export EDITOR
PATH="${HOME}/local/bin:$(go env GOPATH)/bin:${PATH}"
export PATH
if [ -n "${ZSH_VERSION}" ]; then
bindkey -e
setopt localoptions localtraps
fi
